/*
 * Open Surge Engine
 * iconlin.c - xpm icon
 * Copyright (C) 2008-2010  Alexandre Martins <alemartf(at)gmail(dot)com>
 * http://opensnc.sourceforge.net
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <allegro.h>
/* XPM */
static const char *allegico_xpm[] = {
/* columns rows colors chars-per-pixel */
"128 128 197 2",
"   c #016701670167",
".  c #0A9D0A9D0A9D",
"X  c #000014541BDC",
"o  c #000018181F1F",
"O  c #132213221322",
"+  c #1B461B461B46",
"@  c #000017172020",
"#  c #00AB1B71234E",
"$  c #00001E1E2B2B",
"%  c #000027273434",
"&  c #000029293737",
"*  c #00802D2D3B3B",
"=  c #000030303E3E",
"-  c #111130303A3A",
";  c #23B923B923B9",
":  c #2CE42CE42CE4",
">  c #339D339D339D",
",  c #3B913B913B91",
"<  c #000037374747",
"1  c #000037374848",
"2  c #040441415454",
"3  c #000044445A5A",
"4  c #000049495F5F",
"5  c #141444445454",
"6  c #35354C4C5656",
"7  c #3D3D4F4F5656",
"8  c #00004B4B61E1",
"9  c #018152526AAA",
"0  c #0B0B54546C6C",
"q  c #000056567070",
"w  c #00005C5C7777",
"e  c #00005C5C7B7B",
"r  c #000060E07E7E",
"t  c #1A1A61617777",
"y  c #191964647B7B",
"u  c #242462627777",
"i  c #43DD43DD43DD",
"p  c #4BB64BB64BB6",
"a  c #543154315431",
"s  c #525259595C5C",
"d  c #5BF85BFC5BFC",
"f  c #60605E5E5C5C",
"g  c #5BDC61616363",
"h  c #45456D6D7C7C",
"j  c #55556E6E7676",
"k  c #5F5F77777E7E",
"l  c #644364436443",
"z  c #6BFC6BFC6BFC",
"x  c #6F6F78787C7C",
"c  c #746F746D746D",
"v  c #7D7D77777676",
"b  c #71F2777778F8",
"n  c #7BCF7BD27BD0",
"m  c #0000633081E8",
"M  c #000068688787",
"N  c #00806BEB8C0B",
"B  c #08086A6A8989",
"V  c #16166C6C8787",
"C  c #1C1C6A6A8383",
"Z  c #12126C6C8A8A",
"A  c #111170708D8D",
"S  c #1E1E70708989",
"D  c #00006E6E9090",
"F  c #00D472FA960E",
"G  c #0B4B73739393",
"H  c #002A768B9AA1",
"J  c #00C179199D5D",
"K  c #09097A249C46",
"L  c #151577779595",
"P  c #1B9C75F59312",
"I  c #169778F89717",
"U  c #1AC579799640",
"Y  c #12BD7C7C9C9C",
"T  c #1C5C7DFE9C5C",
"R  c #20206D6D8585",
"E  c #2A2A6D6D8383",
"W  c #2D2D75758C8C",
"Q  c #3B3B74748686",
"!  c #30B075758B4B",
"~  c #22A379799494",
"^  c #2F2F7F7F9797",
"/  c #20207B7B9898",
"(  c #2C2C7E7E9898",
")  c #32327DFE9595",
"_  c #39397F7F9494",
"`  c #00007AFBA0A0",
"'  c #FCFC1F1FFCFC",
"]  c #FAFA3F3FFAFA",
"[  c #F7F75E5EF7F7",
"{  c #F4F47D7DF4F4",
"}  c #25A680809D1D",
"|  c #2D2D822C9C9C",
" . c #3C3C80809595",
".. c #30B084039E1E",
"X. c #3BBC83029999",
"o. c #3F3F89899E9E",
"O. c #2A2A8686A2A2",
"+. c #32328989A3A3",
"@. c #3BBC8A8AA221",
"#. c #3C3C9292AEAE",
"$. c #505080808F8F",
"%. c #404083839797",
"&. c #4BCC85059696",
"*. c #474787879B9B",
"=. c #4F4F87879999",
"-. c #57578A8A9A9A",
";. c #5A5A8E8E9F9F",
":. c #7F7F82828484",
">. c #71718F8F9999",
",. c #676791919E9E",
"<. c #737395959F1F",
"1. c #7B7B97979F9F",
"2. c #44C48C8CA4A4",
"3. c #4B4B9090A7A7",
"4. c #5C5C9090A1A1",
"5. c #55559494A8A8",
"6. c #5D5D9797A9A9",
"7. c #51D29B9BB3B3",
"8. c #65659494A3A3",
"9. c #62629696A8A8",
"0. c #666699EFAA54",
"q. c #72729D9DAAAA",
"w. c #78789F9FABAB",
"e. c #7979A2A2AFAF",
"r. c #6B6BABABBEBE",
"t. c #7474A5A5B3B3",
"y. c #845B845C845A",
"u. c #888886868585",
"i. c #8E388E368E36",
"p. c #912591259125",
"a. c #9C1C9C1C9C1B",
"s. c #A1A19C9C9A9A",
"d. c #8504A4A4AE2E",
"f. c #8C8CA5A5AD2D",
"g. c #9090A3A3A8A8",
"h. c #9C9CA8A8ADAD",
"j. c #9494ADADB55F",
"k. c #9A9AAEAEB5B5",
"l. c #9B9BB5B5BEBE",
"z. c #A426A430A434",
"x. c #AAAAA4A4A2A2",
"c. c #A5A5A9A9AAAA",
"v. c #AC4AAC4AAC4A",
"b. c #A4A4B1B1B4B4",
"n. c #A424B6B6BCBC",
"m. c #A2A2B8B8BEBE",
"M. c #ABABB9B9BDBD",
"N. c #B42FB42FB42F",
"B. c #BC3FBC36BC33",
"V. c #C0C0BFBFBEBE",
"C. c #8D8DBFBFCECE",
"Z. c #9696BABAC5C5",
"A. c #A3A3B9B9C0C0",
"S. c #AC56BC66C116",
"D. c #B1B1BF3FC4C4",
"F. c #F1F19C9CF1F1",
"G. c #EEEEBBBBEEEE",
"H. c #ABABC1C1C8C8",
"J. c #B4B4C3C3C7C7",
"K. c #B8B8C5C5C9C9",
"L. c #BCBCC9C9CDCD",
"P. c #A4A4D0D0DDDD",
"I. c #B535D1D1DA59",
"U. c #C42AC428C428",
"Y. c #CC63CC65CC65",
"T. c #CF4FD2D2D453",
"R. c #D49BD495D493",
"E. c #D958D4D4D353",
"W. c #D52AD9D9DB30",
"Q. c #DC7DDC76DC74",
"!. c #E4E4DEDEDDDD",
"~. c #E464E0E0DF5F",
"^. c #E9E9E2E2DFDF",
"/. c #C1C1DADAE261",
"(. c #CCCCDBDBE0E0",
"). c #D0D0DFDFE4E4",
"_. c #EAEAD9D9EAEA",
"`. c #DE1DE322E4A4",
"'. c #D4D4E3E3E8E8",
"]. c #DC5BE9E9ECEC",
"[. c #D0D0EAEAF1F1",
"{. c #D9D9EEEEF5F5",
"}. c #E49BE4A0E4A0",
"|. c #E968E767E767",
" X c #E0E0EBEBEFEF",
".X c #EC36EC3CEC40",
"XX c #F170EFEFEEEE",
"oX c #F6F6F1F1EFEF",
"OX c #FAFAF1F1EFEF",
"+X c #E5E5EE6EF170",
"@X c #E8E8F0F0F2F2",
"#X c #ECECF5F5F8F8",
"$X c #F47CF485F487",
"%X c #FDFDF8F8F6F6",
"&X c #F676FA79FB7A",
"*X c #FF8EFF8FFF8E",
"=X c None",
/* pixels */
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.}.|.{ ' =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.`.}.W.Y.V.N.N.z.a.a.z.N.B.R.Q.{ =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.Q.%X*X*X*X*X*X*X*X*X*X*X*X$XU.h.p.a.v.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.|.*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X*X$XY.a.i.N.|.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.U.*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X*X*X*X&XQ.z.u.U.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X$XB.p.B.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XQ.B.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.XB.p.`.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X' B..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X%XY.a.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.T.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XY.z.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XQ.U.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X$Xv.Y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X_.B..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.U.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.Q.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU.Y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.W.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XQ.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.n N.B.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.u.n a.p.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xc.y.Y.' =X}.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.p.a.B.a.z.Q.@XN.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.$XQ.z.i.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.z.a.z.U.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.c.v.Y.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.a.B.c.v.Q.%X*X*X*X%XB.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xv.*X%X*X%XR.p.c.=X=X=X=X=X=X=X=X=X=X=X[ T.z.n n y.y.i.i.p.i.a.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xv.c i.i.y.y.i.p.a.N.}.=X=X=X=X=X=X=X=X=X=X=X}.z.V.c.U.XX*X*X*X*X*X*X*X&XY.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU.$X*X*X*X*X*XR.a.Y.=X=X=X}.U.c.y.z l c :.i.p.p.i.i.p.p.i.p.i.a.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.p.i.p.i.i.p.p.p.p.i.n n p.U.}.=X=X=X=X=X=Xv.N.B.B.%X*X*X*X*X*X*X*X*X*X*X%XQ.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XR.}.*X*X*X*X*X*X%XY.B.B.p.c l l n i.p.p.i.p.p.i.p.p.i.p.i.p.i.c p.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.v p.i.p.i.p.p.i.p.p.p.p.p.i.c c p.U.=XF.v.T.N.%X*X*X*X*X*X*X*X*X*X*X*X*X*X&X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.$X*X*X*X*X*X&XR.a.c l l n p.p.p.p.p.p.p.p.i.p.p.p.i.p.p.i.p.n c Y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xa.:.p.p.p.p.p.p.p.p.p.p.i.i.p.p.p.p.n a l N.Q.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.*X*X*X*X$XU.i.z d c p.p.i.p.i.p.i.p.p.p.i.p.p.i.p.p.i.i.p.p.y.l N.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X{ n i.i.p.i.p.i.i.p.p.p.p.p.p.p.p.p.i.y.n i.z z B.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XY.*X&X%XT.i.z l y.p.p.p.p.p.i.p.p.p.p.p.p.p.p.p.i.i.p.i.c.a.p.y.l a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.z p.p.i.i.i.p.p.i.i.i.i.p.p.i.p.p.i.p.p.p.i.p.i.l i.$X*X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X$XR.*X$Xa.z d i.p.p.p.p.i.p.i.p.p.i.p.p.i.p.i.p.i.p.y.y..XB.z.p.u.z p.|.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XQ.l p.i.i.U.N.p.p.p.i.p.p.p.p.p.p.p.p.i.i.p.p.p.i.i.p.c p.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU..Xi.d y.i.i.p.p.p.i.p.p.p.p.p.p.p.p.p.i.p.p.n i.|.*X*XY.p.i.i.c i.`.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.z p.p.i.R.*X&Xx.c p.p.p.p.i.p.i.p.p.p.p.p.p.i.p.p.p.p.i.n U.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.z.p i.i.p.p.i.p.p.p.p.p.p.p.i.p.p.p.p.y.c v.@X*X*X*X*X}.i.i.i.z :.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.z p.i.a.Q.*X*X*X&XN.z y.p.i.p.p.i.i.p.p.i.p.p.p.i.p.i.i.i.z N.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.X*XU.a p.p.p.i.p.p.p.p.p.i.p.p.i.p.i.p.n n U.%X*X*X*X*X*X*X}.y.i.i.z y.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xv.z p.u.p.}.*X*X*X*X*X%XW.p.y.p.p.i.p.p.p.p.p.p.p.p.p.i.p.i.p.z N.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.Y.n i.i.p.p.p.p.p.i.p.p.i.i.p.i.p.c n Q.*X*X*X*X*X*X*X*X*X.Xi.i.i.z u.[ =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xa.l p.i.a..X*X*X*X*X*X*X*X*X}.z.c i.p.i.p.p.p.i.p.p.p.p.p.p.i.p.l Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.c c y.i.i.p.p.i.p.p.p.i.i.i.p.c d N.*X*X*X*X*X*X*X*X*X*X*X$Xi.p.u.l p.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xi.l p.y.z.$X*X*X*X*X*X*X*X*X*X*X|.a.c i.p.i.p.i.p.i.i.p.p.i.p.i.c y..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xn y.y.i.i.p.i.p.i.p.p.p.p.p.i.l :.Q.*X*X*X*X*X*X*X*X*X*X*X*X|.y.p.u.l z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xy.z p.y.a..X*X*X*X*X*X*X*X*X*X*X*X*X}.y.n p.p.i.p.p.p.p.p.p.i.i.i.p..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.z y.i.p.p.p.p.p.p.p.i.i.p.n l N.%X*X*X*X*X*X*X*X*X*X*X*X*X*X}.c i.i.l N.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xn z p.y.a.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.c i.i.i.p.i.p.p.i.p.p.y.c }.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.n i.i.i.p.i.p.p.p.p.p.p.z y.`.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.c p.u.z U.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xc z i.i.p.}.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.Xn p.p.p.p.p.p.p.p.i.p.z U.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xz.n i.p.i.p.p.p.i.p.p.p.z N.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.n p.u.n T.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xn z i.i.a.Q.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xc p.p.p.p.p.p.p.p.p.y.c &X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xy.y.p.i.p.p.p.p.p.i.p.c p.XX*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.z p.y.n R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xn c i.p.p.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.Xl p.i.i.i.p.p.i.p.p.l N.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X$Xn y.p.i.p.p.p.p.p.p.:.a , N.%X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.c p.y.u.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xy.c y.p.a.Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.y.> z p.p.p.i.p.p.i.p.v n |.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XR.n u.i.i.p.p.p.i.p.i.b n p.p.d Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.c i.y.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xi.n n p.p.T.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xp.i c p.z y.i.p.p.i.p.p.i.p.l N.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.y.i.i.p.p.i.i.p.p.i.i.i.i.i.}.U.z &X*X*X*X*X*X*X*X*X*X*X*X*X%Xz.c y.n z.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xp.c b p.p.U.*X*X*X*X*X*X*X*X*X*X*X*X*X}.d z i.p.i.i.n p.i.p.p.p.p.p.p.z c.Q.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xc.y.p.p.i.p.p.p.p.i.i.i.i.p.p.i.a.N.n T.*X*X*X*X*X*X*X*X*X*X*X@Xa.n i.v c._.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xz.z n p.u.B.%X*X*X*X*X*X*X*X*X*X*X*XB.l y.p.i.p.p.p.p.p.p.i.p.p.i.p.i.i.:.B.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xa.n p.i.p.p.p.i.p.i.i.p.p.p.i.i.i.i.s.i.N.*X*X*X*X*X*X*X*X*X*X|.y.i.i.z z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xa.g n p.y.N.%X*X*X*X*X*X*X*X*X*X*XN.c i.p.p.p.i.p.p.p.i.i.p.p.i.p.i.p.p.g Q.T.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&Xi.n p.p.p.p.p.i.p.i.i.p.p.p.p.p.p.i.p.i.i.z.*X*X*X*X*X*X*X*X*X.Xl p.i.z a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X|.}.U.p y.i.n z.%X*X*X*X*X*X*X*X*X$XN.b p.i.p.i.p.i.p.p.i.i.p.i.p.p.p.p.p.i.:.z.R.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.i.y.p.p.p.p.p.p.p.p.i.p.i.i.p.p.i.p.i.i.y.c a.*X*X*X*X*X*X*X%X.Xa a.y.z a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=XR..X*XR.p y.u.n z.@X*X*X*X*X*X*X*X$Xc.z p.p.p.p.p.p.p.p.i.i.p.i.p.p.p.p.p.i.p.p.z %X|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.:.i.i.p.p.i.p.p.p.p.i.p.p.p.p.p.p.p.p.p.p.y.l c.*X*X*X*X*X*X*XR.d p.y.c z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=XY.%X*X*XQ.p y.:.i.p.}.*X*X*X*X*X*X%Xv.d u.p.p.p.p.i.p.p.p.p.p.i.p.p.p.p.i.p.p.p.i.z R.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xx.c p.p.p.i.p.p.i.p.p.p.p.p.p.p.i.p.p.p.i.i.i.y.z V.*X*X*X*X*X%Xh.c i.:.n c.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X}.R.%X*X*X*X|.d b y.i.i.R.*X*X*X*X*X%XN.l y.p.p.i.p.p.p.i.p.p.i.i.p.p.p.i.p.p.i.i.p.i.i.i.*X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%Xa.c p.p.p.p.p.p.p.p.p.i.p.p.i.p.p.i.p.i.p.p.p.p.y.v R.*X*X*X*X*Xn y.i.v :.V.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=XR.`.*X*X*X*X*X$Xn z y.p.y.U.*X*X*X*X*XN.c v p.p.p.p.p.i.p.p.p.p.p.p.i.p.i.p.p.p.p.p.p.p.p.z *X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X$Xp.c p.p.p.p.i.i.p.p.p.p.p.i.p.p.p.p.p.p.p.p.p.i.i.:.n Q.*X*X*XQ.c p.i.v :.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=XR.}.*X*X*X*X*X*X&Xa.d u.i.i.N.&X*X*X*XY.n b p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.i.p.i.n R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.u.n p.p.p.i.p.p.p.i.p.p.p.p.p.p.p.p.i.p.p.i.i.p.p.i.c a B.%X*XY.c p.i.n b ' =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X}.U.&X*X*X*X*X*X*X*X%XB.p i.u.i.x..X*X*X}.y.c p.i.p.i.p.p.i.p.p.i.p.p.i.p.p.p.p.i.p.p.i.p.p.p.p.i.p.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XR.:.y.p.p.i.i.p.p.p.p.p.i.p.p.i.p.p.i.p.p.p.p.p.p.p.p.i.c l B..XB.y.i.y.n y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=XY.W.*X*X*X*X*X*X*X*X*X*XQ.a u.u.p.c.R.&X*Xp.c p.p.p.p.i.p.p.i.p.p.i.p.p.i.p.i.p.p.i.p.p.i.p.p.p.p.i.c *X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.v y.i.p.p.p.i.p.p.i.i.p.p.i.p.p.i.p.p.i.p.p.i.p.i.i.i.i.l n B.a.y.p.y.n a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=XB.|.*X*X*X*X*X*X*X*X*X*X*X.Xc n i.i.a.R.*XN.c p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.i.c R.*X%X*X*X*X*X*X*X*X*X*X*X*X*XK.c i.i.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.i.p.n l c c y.i.y.c v.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=XN.*X*X*X*X*X*X*X*X*X*X*X*X*X$Xa.z p.u.a.K.R.i.u.p.p.p.p.p.p.p.p.p.p.i.p.p.p.p.i.p.p.i.p.p.p.p.i.p.p.i.p.y.z.*X*X*X*X*X*X*X*X*X*X*X*X*X%XB.n i.p.i.p.i.p.p.p.p.p.p.p.p.i.p.p.p.p.i.i.p.p.p.p.p.p.p.p.c z d p.i.i.z R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=XU.R.*X*X*X*X*X*X*X*X*X*X*X*X%XB.d p.p.v N.z.y.i.p.p.i.p.p.i.p.p.i.p.p.i.p.p.i.p.p.p.p.i.p.p.i.p.p.i.p.p.i.y.*X*X*X*X*X*X*X*X*X*X*X*X*X%Xv.c p.p.p.p.p.i.p.p.i.i.p.p.i.p.p.i.p.p.p.p.p.i.p.p.i.i.p.p.y.l c i.i.y.c =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X|.v.}.*X*X*X*X*X*X*X*X*X*X*XQ.l i.p.y.i.u.i.p.i.p.p.i.p.p.p.p.p.p.p.p.p.i.p.p.p.i.p.p.p.p.p.p.p.p.p.p.i.n $X*X*X*X*X*X*X*X*X*X*X*X*X&Xz.n i.p.p.p.p.p.p.i.p.p.i.p.p.p.p.p.p.p.p.p.i.p.p.p.p.p.p.i.p.i.i.i.i.l n =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=XQ.c.Q.*X*X*X*X*X*X*X*X*X}.n n p.i.i.i.i.p.p.p.p.p.p.i.p.i.i.i.p.p.p.p.p.p.p.p.p.p.i.p.p.p.p.i.p.i.i.y.U.*X*X*X*X*X*X*X*X*X*X*X*X$Xa.n p.p.i.p.p.p.p.p.p.p.p.p.p.p.p.i.p.p.i.p.p.p.i.p.p.p.p.p.p.i.p.i.i.y.l =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X}.z.R.%X*X%X*X*X*X*X$Xa.l p.p.i.i.i.i.i.p.i.p.p.p.i.p.a.p.i.i.p.p.i.p.i.i.p.p.i.p.i.i.p.i.p.p.p.y.a.*X*X*X*X*X*X*X*X*X*X*X*X.Xa.n p.i.p.p.i.i.p.p.i.i.p.p.i.i.p.p.p.p.i.p.i.i.p.i.p.p.p.i.i.i.i.p.i.i.n B.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=XN.v.$X*X*X*X%X*XB.d i.p.p.p.i.p.p.p.p.i.p.p.p.p.p.i.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.i.p.y.y.*X*X*X*X*X*X*X*X*X*X*X*X}.i.y.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.i.p.p.i.i.i.i.i.i.p.p.p.n p.i.i.i.y.i.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X`.z.N.Y.&X*XQ.z n p.p.p.p.p.i.i.i.p.p.p.i.p.p.p.i.p.p.p.p.p.p.p.i.p.p.p.p.p.p.p.i.p.p.y.n $X*X*X*X*X*X*X*X*X*X*X*XQ.i.u.p.p.i.p.p.i.p.p.i.p.p.p.i.p.i.i.p.u.z n i.c n n y.a.a.p.p.a d p.i.p.u.n =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X] Q.T.R.p.c p.i.p.p.p.p.a p.i.p.p.i.p.p.p.p.p.p.i.i.i.p.p.p.i.p.p.i.i.p.p.i.i.p.y.n R.*X*X*X*X*X*X*X*X*X*X*XQ.u.i.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.b l d f c n c z c z d i a i.z ; p.i.i.i.y.Y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.n p.p.p.p.p.l d p.i.p.a.p.c l d p p d z i.p.p.p.i.p.p.p.p.p.p.i.p.p.p.i.y.B.*X*X*X*X*X*X*X*X*X*X*XR.y.p.p.p.p.p.i.p.i.p.p.p.p.p.p.n g l c a.N.R..X*X*X*X*X*X*X$Xi.l   c p.p.i.u.v.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.i.i.i.p.p.p.+ y.p.i.l , p a.B.Y.R.Y.N.y.a g i.p.i.p.i.p.i.i.p.p.i.i.i.i.n z.*X*X*X*X*X*X*X*X*X*X*XR.n p.i.p.i.p.p.p.p.p.i.p.p.u.d z a.U.%X*X*X*X*X*X*X*X*X*X*X*X*Xn + > p.i.i.y.a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.a.i.i.p.p.n O p.a p i.R.*X*X*X*X*X*X*X*X*XY.n l i.p.p.p.p.i.p.p.p.i.i.p.n a.*X*X*X*X*X*X*X*X*X*X*XY.c p.p.p.i.p.p.p.p.i.p.i.z l a.Q.*X*X*X*X*X*X*X*X%X&X*X*X*X*X*Xp.,   i.p.p.:.p.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.p.i.p.p.p.p ; n B.}.*X*X&X*X*X*X*X*X*X*X*X*X*XT.c v p.p.i.p.p.p.i.i.i.p.n p.*X*X*X*X*X*X*X*X*X*X*XU.c p.p.p.p.p.p.p.i.i.y.a i.Q.*X*X*X*X*XXXR.B.U.R.R..X*X*X*X*X*Xp.d   l p.p.:.i.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.i.i.p.i.a.: > l |.*X%X|._..X$X.X&X%X*X*X*X*X*X*X*XB.z u.i.i.p.p.p.p.i.p.y.p..X*X*X*X%X*X*X*X*X*X*XV.z p.i.p.p.i.p.p.i.z l Y.*X*X*X*X&XQ.R.`.Q.R.v.a.l d z i.Q.*X*Xa.z   > a.p.n i.G.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.y.i.p.p.p.O p l .X%XK.U.N.: i p.B.|.*X*X*X*X*X*X*X*X&Xi.c i.p.i.p.p.p.p.y.a.|.*X*X*X*X*X*X*X*X*X%XN.c p.p.p.i.p.i.i.p h.%X*X*X*X%XU.B.N.i.i.z p.N.Y.}.v.i.c B.*X*Xz.c . O p.p.y.i.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.y.p.i.i.i.  a l .X*X*X|.a.h.V.|.&XB.z.}.*X*X*X*X*X*X*X*XN.c p.p.p.i.p.i.i.p.Q.*X*X*X*X*X*X*X*X*X@Xa.c p.p.p.i.p.:.a R.*X*X*X*XQ.i.z i.z.l a.}.$XQ.B.*XQ.i.N.$X*X*Xa.n .   y.p.i.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.n p.p.p.y.  a l .X*X*X}.R.%X*X*X*X%X*XXXc.Y.*X*X*X*X*X*X*X}.d i.i.p.p.i.i.p.R.*X*X*X*X*X*X*X*X*X|.y.n p.p.p.p.z y.%X*X*X*X%XN.l a.c y.}.*X*X*X*X*X%X*XR.y.U.*X*X*Xa.c O . c p.y.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.n p.p.p.c   a l |.*X*XQ.Y.*X*X*X*X*X*X*X*X.XN.W.*X*X*X%X*X*X|.d i.i.p.p.i.i.Y.*X*X*X*X*X*X*X*X*X}.c y.p.p.p.z z.&X*X*X*X&Xx.p.c c Q.*X*X*X*X*X*X*X*X*XQ.n B.*X*X*Xi.n O   l p.i.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.n p.i.p.d   p l Q.*X*XQ.U.*X*X*X*X*X*X*X*X*X$XN.c.$X*X*X*X*X*X}.l y.p.i.p.y.U.*X%X*X*X*X*X*X*X*XQ.z i.i.p.n a.$X*X*X*X$Xy.v l K.*X*X*X*X*X*X*X*X*X*X*X}.p.Y.*X*X*Xy.y.O   l p.y.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.n p.p.a.p   i z U.*X*XQ.U.*X*X*X*X*X*X*X*X*X*X%XK.z.}.*X*X*X*X*X.Xc y.p.p.y.B.*X*X*X*X*X*X*X*X*XR.l i.i.p.i.}.*X*X*X*Xc g a..X*X*X*X*X*X*X*X*X*X*X*X*XQ.a.R.*X*X*Xl y..   d p.y.p.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.n p.p.p.i   : c N.*X*XR.U.*X*X*X*X*X*X*X*X*X*X*X%XR.p.R.*X*X*X*X*X$Xb u.p.u.B.*X$X$X*X*X*X*X*X*XE.d i.z.i.R.*X*X*X%Xs * C }.*X*X*X*X*X*X*X*X*X*X*X*X*XR.p.`.*X*X%Xp y.    d a.y.p.|.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.n p.p.a.,   ; y.a.*X*XR.U.*X*X*X*X*X*X*X*X*X*X*X*X*X`.:.B..X*X%X*X*X|.c p.y.B.*X*X*X*X*X*X*X*X*XW.l a.i.U.*X*X*X%Xg 1 F K d.*X*X*X*X*X*X*X*X*X*X*X*X&XB.a.|.*X*XQ.a c     l p.y.p.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.c p.p.p.i   O i.n *X*XR.B.*X*X*X*X*X*X*X*X*X*X*X*X*X9.C.c.y.$XXX*X*X*XR.z y.N.*X*X*X*X*X*X*X*X*XR.d y.z..X*X*X&Xd 5 F J F *.%X*X*X*X*X*X*X*X*X*X*X*X$Xz.v.*X*X*XN.l d     z p.y.a.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.n p.p.p.i   . y.z *X*X}.U.%X*X*X*X*X*X*X*X*X*X*X*X|.@.r.*XN.:.#X&X*X*X%XB.f N.*X*X*X*X*X*X*X*X*XQ.l i.Y.*X*XQ.i u.$.J J F W `.*X*X*X*X*X*X*X*X*X*X*X}.p.U.*X*X*Xy.c ,     n p.y.z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.n p.p.y.p     n l }.*X}.B..X*X*X*X*X*X*X*X*X*X*X*XW...7.@X*Xj x }.*X*X*X`.c p.%X*X*X*X*X*X*X*X*XQ.c v.&X&X|.p d .Xf.F J F S L.*X*X*X*X*X*X*X*X*X*X*XR.i.|.*X*X*Xd y.+   . i.p.y.z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.y.i.p.z p     d n U.*X$XY.}.*X*X*X*X*X*X*X*X*X*X*XW...7. X*XW 9 ! W.*X*X*Xa.c $X*X*X*X*X*X*X*X*X}.u.Y.*X$X:.7 l.*Xk.F J F P M.*X*X*X*X*X*X*X*X*X*X*XU.z.*X*X*XR.a n .   + p.i.i.v.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.y.i.p.c i     , i.p.*X*XR.Q.*X*X*X*X*X*X*X*X*X*X*XW...+.].*X>.F 9 f.|.*X*XY.z Y.*X*X*X*X*X*X*X*XR.y.%X*Xi.v ;.t.*XA.m e ` I S.*X*X*X*X*X*X*X*X*X*X%XN.z.*X*X*Xp.l l     : a.i.i.U.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X|.i.n p.y.;     + p.v *X*XR.R.*X*X*X*X*X*X*X*X*X*X*XQ.@./ '.*Xf.q J t B.%X$XU.z.B.&X*X*X*X*X*X*X*XQ.i.%Xa.l !.2.0.&XD.$ 4 J L n.*X*X*X*X*X*X*X*X*X*X.Xz.c.*X*X.Xn y.>     p p.i.i.Q.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xp.c p.i.+     . y.n Q.*XQ.R.*X*X*X*X*X*X*X*X*X*X*X.X3.Z ).*Xg.2 J K ,.a.p.a.a.Y.*X*X*X*X*X*X*X*XY.l U.z U.$X~ 0.%XS.X * ` L m.*X*X*X*X*X*X*X*X*X*X}.:.U.*X*X&Xc y.O     c p.i.i.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xa.b p.i.;       l u.z.*X}.U..X*X*X*X*X*X*X*X*X*X*XXX5.e /.*Xx $ F F T n y.n i.B.*X*X*X*X*X*X*X%XB., a z.*X+XP 4.*Xj.X < F I S.*X*X*X*X*X*X*X*X*X*XQ.i.Q.*X*XU.u.l .   . p.i.y.p.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xv.n p.p.,       > i.b &X*XB.Q.*X*X*X*X*X*X*X*X*X*X%X0.w I.*X6 # F F Y h.c d i.Y.*X*X*X*X*X*X*X&XB.> > N.*X{.P &.*X<.X & F T J.*X*X*X*X*X*X*X*X*X&Xx.N.}.XX*Xp.i.>     : p.p.i.z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.n i.p.d .     O i.c z.%XB.Y.*X*X*X*X*X*X*X*X*X*X*Xe.m 2./.- o M J O.R.Q.l f R.*X*X*X*X*X*X*X*XY.i z &X*X X~ ! *Xh # * F } K.*X*X*X*X*X*X*X*X*X.Xa.v.T.&X!.p.n O     a i.i.u.T.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.y.n p.z O       z n c &X}.B.|.*X*X*X*X*X*X*X*X*X*Xj.G m C * o N H | }.$Xp.d Y.*X*X*X*X*X*X*X*XY., N.*X*X#X( C `.0 o & ` O.T.*X*X*X*X*X*X*X*X%XB.N.i.R.*XN.i.a       b i.i.y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xi.n p.n ;       : p.c N.*Xz.R.*X*X*X*X*X*X*X*X*X*XH.I F F 3 # N H  .oX*XN.p U.*X*X*X*X*X*X*X*XY.c W.*X*X*XX.B Q e # < J / `.*X*X*X*X*X*X*X*X*Xp.z B.|.|.a.:.;     : c p.i.i.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xz.c i.i.;       O y.z n &XY.p.U.%X*X*X*X*X*X*X*X*X(.^ F J 8 # N H &.*X*XR.z B.*X*X*X*X*X*X*X%XN.a &X*X*X*X-.J F m * 9 J | .X*X*X*X*X*X*X*X*XY.d n W.*XB.y.d .     l n u.z n c.a.z.v.B.}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.n i.p.,         i a.d z.%Xa.a.|.*X*X*X*X*X*X*X*X#X%.D J 9 % F J <.*X*X$Xn v.*X*X*X*X*X*X*X*XN.f *X*X*X*Xw.K H M q M F  .&X*X*X*X*X*X*X*X*Xa.a }.Q.$Xa.n :     O a l f i z.|.*X*X*X*X|.U.p.i.W.=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xy.n p.d         + n c n T.R.a.c.%X*X*X*X*X*X*X*X*X8.N ` m 4 J K b.*X*X%Xi.c.*X*X*X*X*X*X*X%XV.n *X*X*X*XD.Y F H r J F =.*X*X*X*X*X*X*X*X.Xy.U.Y.*XY.n d .     p y.i.i.i.p.i.c p.Q.*X*X*X*X%X$Xv.p.|.=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XG.Q.=XN.y.i.n .         > p.z U.W.Y.|.|.*X*X*X*X*X*X*X*XZ.A F F F H G Q.*X*X*Xa.c.*X*X*X*X*X*X*X*XR.a.*X*X*X*X~.T J J J J G q.*X*X*X*X*X*X*X*XU.z.}.Q.$Xz.c :       y.i.p.i.i.i.i.i.p.i.y.W.*X*X*X*X*X%XR.a.).=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XB.z.B.R.}.|.}.B.c u.p.;         . p f y.z.a.N.B.z.U.|.*X*X*X*X*X{.E F J H H ! %X*X*X*Xv.c.*X|.z.n c :.D.*XV.c.*X*X*X*X*XX.H J F F V I.*X*X*X*X*X*X*X}.c N.y.z.y.d i .     p i.p.i.p.p.p.p.i.i.i.p.v z Q.*X*X*X*X*X%XU.N.=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=XN.v.R..X*X*X*X*X*X*X*Xy.g z ,   O O O l p.U.$X*X}.K.Q.*X}.B.B.Y.Q.$X*X*X6.M F J J q.%X%X*X*XU.p.B.U.|.*X*X%XW.N.v.a.i.c.$X*X*Xj.K J J F ! *X*X*X*X*X*XR.N.p.R.z.}.XXR.i.f +     n p.p.p.p.i.p.p.i.p.p.p.p.i.a R.*X*X*X*X*X*X|.v.}.=X=X=X=X",
"=X=X=X=X=X=X=X=X|.v.B..X*X*X*X*X*X*X*X|.a.l n y.p.c .   . c *X*X*X*X*X*X%X%X*X*X*X.XY.B.Y.|.%X[.t F F O.R.*X*XXXB.i.p.}.*X*X*X*X*X*XOXv.N.R.T.i.N.*XY.Y J J K m.*X*X*X*X%X}..XR.U.R.|.*X*X&XQ.V.i   i i.p.p.p.i.p.p.p.p.p.i.i.p.i.p.z %X*X*X*X*X*X*X$XN.}.=X=X=X",
"=X=X=X=X=X=X' N.B.%X*X*X*X*X*X*X*X$Xz.d n p.p.i.i.i.>   ; Q.*X*X*X*X*X*X%X*X*X*X*X*X*X$XB.x.K.OXP.u o.z.*X%XK.a.T.&XR.|.*X*X*X*X*X*X|.i.*X$XY.R.Y.a.E.) F F  .*X*X*X*X*X*X@XR.R..X*X*X*X*X*X*X*XY.i.a y.p.p.p.p.p.p.p.p.p.i.p.p.p.i.p.v.*X*X*X*X*X*X*X%Xc.] =X=X",
"=X=X=X=X=XY.v..X*X*X*X*X*X*X*X*X$Xi.l p.p.i.p.p.p.p.z   > &X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.XB.B.!.Q.|.R.N.Y.*X*X*XU.}.*X*X*X*X*X*XR.z *X*X*X$XY..Xv.b G #.U.*X*X%X&X}.U.N.Y.%X*X*X*X*X*X*X*X*X*X}.i.n i.p.i.p.i.p.p.i.p.p.p.i.p.i.z.N.&X*X*X*X*X*X*X*X.XU.=X=X",
"=X=X=X=XB.U.*X*X*X*X*X*X*X*X*X.Xi.l p.i.i.p.i.p.i.i.p.i : }.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&X*X*X*X*X*X*XV.Q.*X*X*X*X*X*XR.p.*X*X*X*X*X|.%X.Xx.i.z.a.z.N.U.Y.|.*X*X*X*X*X*X*X*X*X*X*X*X*Xa.z i.p.i.p.p.i.p.p.p.p.p.p.i.i.R.a.$X*X*X*X*X*X*X*X*XN.=X=X",
"=X=X=XB.Q.*X*X*X*X*X*X*X*X*X%Xz.d a.p.p.p.p.p.p.p.p.i.z a U.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.Q.Q.i.z z i.v.N.a.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.y.i.i.p.p.p.p.p.p.p.i.i.p.i.z.y.%X*X*X*X*X*X*X*X*X*XY.}.=X",
"=X=X{ B.*X*X*X*X*X*X*X*X*X*X|.z i.p.p.p.p.p.p.p.p.i.i.n d a.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.i.+           z a.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.a.i.p.p.i.p.p.p.i.p.p.i.p.z v.*X*X*X*X*X*X*X*X*X*X*Xv.=X=X",
"=X=X[ v.*X*X*X*X*X*X*X*X*X*X}.b z p.i.i.p.i.i.p.p.i.i.y.l i.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xx.+           . i.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.p.p.i.p.p.p.i.p.p.p.p.y.l W.&X*X*X*X*X*X*X*X*X*X*XY.Y.=X=X",
"=X=X=XT.Y.*X*X*X*X*X*X*X*X*X&Xi.z i.i.i.p.p.p.p.p.p.p.u.l p.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xa           z *X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&Xi.y.i.p.p.i.i.i.i.p.i.a p.&X*X*X*X*X*X*X*X*X*X*X*XY.B.=X=X=X",
"=X=X=X=XB.R.*X*X*X*X*X*X*X*X*XR.v l p.p.p.i.i.p.p.i.i.i.n z.B.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&Xa.> . ; Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xz.u.p.i.p.p.i.i.i.c a n Q.*X*X%X*X*X*X*X*X*X*X*X*XY.B.=X=X=X=X",
"=X=X=X=X{ N.Q.*X*X*X*X*X*X*X*X*XT.c z a.p.p.p.p.p.i.p.i.y.z B.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X$X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XQ.Y.%X*X*X*X*X*X*X*X*X*X*X*X*X*X}.i.u.p.p.p.p.i.g p l |.*X*X*X*X*X*X*X*X*X*X*X*X*XY.B.=X=X=X=X=X",
"=X=X=X=X=XF.N.Q.*X*X*X*X*X*X*X*X*X|.y.d u.p.p.i.i.p.i.p.u.c y.K.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&XY.}.*X*X*X*X*X*X*X*X*X*X*X*X*X&Xa.:.p.i.i.i.i.y.u.i.p.|.*X*X*X*X*X*X*X*X*X*X*X*XY.B.=X=X=X=X=X=X",
"=X=X=X=X=X=X=Xv.Q.*X*X*X*X*X*X*X*X*X*XR.c a z y.p.p.p.i.p.u.l c Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.N.*X*X*X*X*X*X*X*X*X*X*X*X*X%Xz.n p.p.i.p.p.p.i.i.i.a.Q.*X*X*X*X*X*X*X*X*X*X%XK.N.=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=Xx.W.*X*X*X*X*X*X*X*X*X*X*X$XN.c a a l y.p.i.u.l z R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.v.*X*X*X*X*XD.Y.%X*X*X*X*X*X}.:.b p.i.p.p.p.i.p.p.p.p.v.R.*X*X*X*X*X*X&X*X*X$Xv.Y.=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=Xv.D.%X*X*X*X*X*X*X*X*X*X%X*X*XB.N.y.p.i.p.i.i.n l U.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%Xc.Y.*X*X%X*XQ.z.U.Q.%X*X*X*X*X|.c c p.p.p.p.i.i.p.p.i.p.a.N.Y.*X*X*X*X*X*X*X*XR.i.=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X~.i..X*X*X*X*X*X*X*X*X*X*Xc.%Xz p.i.p.i.i.i.u.n d V.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*XR.p.&X*X*X*X&XN.U.*XB..X*X*X*X*X.Xc :.p.p.p.p.p.p.p.p.p.p.p.p.B.Y.*X*X*XR.$X%XT.y.Q.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=Xv.a.*X*X*X*X*X*X*X*Xv.$XU.n p.i.p.i.p.p.i.c n a c.*X*X%X%X|.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU.i.}.*X*X*X*XR.z.$X*XY.Q.*X*X*X*XR.y.N.u.p.p.p.p.p.p.p.i.p.p.i.a.B.Y.*X*X*Xi.z z.=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xc.p.}.*X*X*X*XU.v.|.i.i.i.p.p.p.p.i.p.p.z i.a.a $X*XXXv.B.v.&X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.B.U.z.p.N..X%X*X*X*X.Xa.Q.*X*X*Xz.Q.*X*X*XN.U.*X}.c p.i.i.p.p.i.p.p.p.p.i.a.B.Y.*X*X*X*Xv.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.z.i.i.c a.`.*Xc p.p.p.p.p.p.i.p.p.i.a.d R.z a.*X|.N.%XN.Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&X$X&X*X*X*X*X*X*Xv.B.*X*X*X*XB.Y.*X*XY.N.&X*X*X%XN.z a.i.p.p.p.i.p.p.i.i.a.B.E.*X*X*X*X%XN.=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY..X*X%Xc p.i.p.p.p.i.p.p.p.u.c }.U.B.Y.z B.Y.Y.*XQ.B.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X*X*X*XW.z..X*X*X&X*X|.U..XY.B.}.*X*X*X*X*X$Xa.z p.i.p.i.p.p.p.p.i.p.N.Q.*X*X*X*X*XB.G.=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XU.Q.*X*X&Xc i.p.p.p.p.i.i.p.c a.$X*X*X$XN.N.h.p.i.Y.*X*XR.v.}.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*Xv.Y.*X*X*X*X*X*XY.z.U.|.*X*X*X*X*X*X*X*X%Xa.c p.p.p.p.p.i.p.i.i.c.*X*X*X*X*X*X&Xv.=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.U.*X*X*X%Xb p.p.p.i.p.p.n n R.*X*X*X*X*X*X|.N.z.c p..X*X*X*XY.N.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X*X*X*X.XN..X.X%X*X*X*X*X.XU.}.*X*X*X*X*X*X*X*X*X*X*X*XV.z y.p.i.i.i.i.p.p.N.*X*X*X*X*X*X*XB.F.=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X{ Y.|.*X*X*X*Xi.p.p.p.y.c n U.*X*X*X*X*X*X*X*X%X*X*X*XN.i.U.`.%X*X*X}.z.v.}.*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X&XR.a.U.@X*X*X*X*X*X*XQ.Y.*X*X*X*X*X*X*X*X*X*X*X*X*X*X&Xa.z n u.p.a.x.Y.Y.*X*X*X*X*X*X*X%XN.=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.Y.*X*X*X*X*XY.c.n f i.}.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU.Q.*X*X*X*X*X%XY.:.p.}.*X*X*X*X*X*X*X*X*X*X&XQ.U.a.z.Y.%X*X*X*X*X*X*X$XY.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XW.a.:.p.v.v..X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.B.*X*X*X*X*X*X*XR.|.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.}.*X*X*X*X*X*X&XN.:.U.%X*X*X*X*X*X*X*X%X.XQ.v.i.B.%X*X*X*X*X*X*X*X}.V.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.U.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.XR.*X*X*X*X*X*X*X*X%Xv.|.*X*X*X*X*X*X*X|.}.}.a.v.B.v.a.i.n l :.B.W.}.*X*X*X*X*X*X*X*X$XY.@X*X%X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X[ N.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*Xy.&X%X*X*X*X$XB.a.B.R.}.:.}.*X*X*X*X*X*X*X*X*X*XN.K.|.*X*X|.U.@X$X}.&X*X*X*X*X*X*X*X*X.XU.%XW.c.p.h.V.XX*X*X%X*X*X*X*X*X*X*X*X*X*X%X%X*X*X*X*X*X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XR.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X|.z }.*X*XY.z.N..X%X*X*X*X*X.Xa.%X*X*X*X*X*X*X*X*X*X*X.X%X*X*X%X%X*X*X$X%X*X*X*X*X*X*X*X$Xy.z.!.&X%X*X&X$XXXU.p.z.$X*X*X*X*X*X*X*X*X*X*Xc.*X*X*X*X*X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=Xv.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XY.y.z.Y.a.Y..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XK.N.U.*X*X*X*X*X*X*X*X*X*X$XR.h.i.B.Y..X*X*X*X*X*Xp.T.*X*X*X*X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X|.U.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XB.N.u.c.Q.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.$X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XoXN.Y.*X*X*X*X*X*XT.U.U.z.N.U.Q..X$X$X&X%X.Xz.=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XK..X*X*X*X*X*X*X*X*X*X*X*X*X*X*X.Xv.Y.U.N.v.%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X&XV.T.*X*X*X*X*X*X*X$XB.=X=X=X}.R.Y.Y.U.U.U.Y.=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=Xx.*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.z.|.R.B.&X|.z.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XN.R.*X*X*X*X*X*X*X*X%Xv.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=XN.*X*X*X*X*X*X*X*X*X*X*X*X%XN.v.=X=XR.}.%X*X*XY.c.$X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XN.Q.*X*X*X*X*X*X*X*X*X*XN.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=XQ.Y.*X*X*X*X*X*X*X*X*X*X*XR.i.}.=X=XQ.R.*X*X*X*X*X*Xa.R.|.}.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU.[ =X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=XY.}.*X*X*X*X*X*X*X*X%XQ.y.R.=X=X=X=XQ.Q.*X*X*X*X*X*X*XB.p .X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.Q.v.@X*X*X*X*X%X*X*X*X*X*X*X*X*XY.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=XN.%X*X*X*X*X*X*X$XN.n }.=X=X=X=X=X=XT.|.*X*X*X*X*X%X$Xc i f h.R.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.l z.Q.*X%X*X*X&X*X*X*X*X*X*X*X*XY.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X}.p.}..X`.U.p.y.U.=X=X=X=X=X=X=X=X}.U.%X*X*X*X*X*XoXp.d n p.i.c Y.*X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X}.z z n d p p.R.*X&X|.*X*X*X*X*X*X*X*XR.R.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X}.R.}.=X=X=X=X=X=X=X=X=X=X=X=XY.N.*X*X*X&X*XN.b p n p.i.i.p.a.u.:.a.U.*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%X$Xp.z i.p.i.p.p.i.c p i z z.}.*X*X*X*X*X%XY.Y.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.B.*X*X*XR.c d i l p.i.p.i.l l n R..X%X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XQ.i.n a.p.p.i.p.i.p.i.p.p.i.n z a i d z y.N..X&X}.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X",
"=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=XY.Q.%XR.y.z i.a.l i.p.n d y.R.*X$X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X%XQ.Q.Q.}.Y.N.y.y.i.p.i.p.p.i.p.p.p.p.p.p.i.u.n z l l i.B.G.=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X"
};
#if defined ALLEGRO_WITH_XWINDOWS && defined ALLEGRO_USE_CONSTRUCTOR
extern void *allegro_icon;
CONSTRUCTOR_FUNCTION(static void _set_allegro_icon(void));
static void _set_allegro_icon(void)
{
    allegro_icon = allegico_xpm;
}
#endif
